# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kurrent/agent/v2/usage.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'kurrent/agent/v2/usage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ckurrent/agent/v2/usage.proto\x12\x10kurrent.agent.v2\x1a\x1cgoogle/protobuf/struct.proto\"\xae\x02\n\nTokenUsage\x12!\n\x0cinput_tokens\x18\x01 \x01(\x03R\x0binputTokens\x12#\n\routput_tokens\x18\x02 \x01(\x03R\x0coutputTokens\x12!\n\x0ctotal_tokens\x18\x03 \x01(\x03R\x0btotalTokens\x12.\n\x13\x63\x61\x63hed_input_tokens\x18\x04 \x01(\x03R\x11\x63\x61\x63hedInputTokens\x12)\n\x10reasoning_tokens\x18\x05 \x01(\x03R\x0freasoningTokens\x12\x14\n\x05model\x18\x06 \x01(\tR\x05model\x12\x44\n\x11\x61\x64\x64itional_counts\x18\x07 \x01(\x0b\x32\x17.google.protobuf.StructR\x10\x61\x64\x64itionalCountsB\x17\xaa\x02\x14Kurrent.Agent.Schemab\x08\x65\x64itionsp\xe9\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kurrent.agent.v2.usage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\024Kurrent.Agent.Schema'
  _globals['_TOKENUSAGE']._serialized_start=81
  _globals['_TOKENUSAGE']._serialized_end=383
# @@protoc_insertion_point(module_scope)
