# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kurrent/agent/v2/value_types.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'kurrent/agent/v2/value_types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"kurrent/agent/v2/value_types.proto\x12\x10kurrent.agent.v2\x1a\x1cgoogle/protobuf/struct.proto\"\xb9\x01\n\x08ToolSpec\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12%\n\x0b\x64\x65scription\x18\x02 \x01(\tH\x00R\x0b\x64\x65scription\x88\x01\x01\x12:\n\x0cinput_schema\x18\x03 \x01(\x0b\x32\x17.google.protobuf.StructR\x0binputSchema\x12\x1b\n\x06source\x18\x04 \x01(\tH\x01R\x06source\x88\x01\x01\x42\x0e\n\x0c_descriptionB\t\n\x07_source\"\xe9\x01\n\x0b\x41gentConfig\x12\x30\n\x05tools\x18\x01 \x03(\x0b\x32\x1a.kurrent.agent.v2.ToolSpecR\x05tools\x12\x18\n\x07plugins\x18\x02 \x03(\tR\x07plugins\x12J\n\x14\x63onversation_manager\x18\x03 \x01(\x0b\x32\x17.google.protobuf.StructR\x13\x63onversationManager\x12\x42\n\x10model_parameters\x18\x04 \x01(\x0b\x32\x17.google.protobuf.StructR\x0fmodelParameters\"{\n\x0cToolCallInfo\x12\x17\n\x07\x63\x61ll_id\x18\x01 \x01(\tR\x06\x63\x61llId\x12\x1b\n\ttool_name\x18\x02 \x01(\tR\x08toolName\x12\x35\n\targuments\x18\x03 \x01(\x0b\x32\x17.google.protobuf.StructR\targumentsB\x1e\xaa\x02\x1bKurrent.Agent.Schema.Eventsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kurrent.agent.v2.value_types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\033Kurrent.Agent.Schema.Events'
  _globals['_TOOLSPEC']._serialized_start=87
  _globals['_TOOLSPEC']._serialized_end=272
  _globals['_AGENTCONFIG']._serialized_start=275
  _globals['_AGENTCONFIG']._serialized_end=508
  _globals['_TOOLCALLINFO']._serialized_start=510
  _globals['_TOOLCALLINFO']._serialized_end=633
# @@protoc_insertion_point(module_scope)
